# Only Python
# FROM python:3.10-slim

# NVIDIA CUDA, no PyTorch
# FROM nvidia/cuda:12.3.1-base-ubuntu22.04 - 87MB
# FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04 - 1.27GB
# FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04 - 1.93GB
# FROM nvidia/cuda:12.3.1-devel-ubuntu22.04 - 3.66GB

# NVIDIA NeMo - Framework: 17.75GB, Gemma: 28.91GB
# FROM nvcr.io/nvidia/nemo:24.01.gemma
FROM nvcr.io/nvidia/nemo:24.01.framework

# NVIDIA PyTorch - 9.96GB
# FROM nvcr.io/nvidia/pytorch:24.01-py3

# Official PyTorch - Devel: 8.44GB - Runtime: 3.41GB (can't build Apex with runtime)
# FROM pytorch/pytorch:latest - Same as below runtime image
# FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-runtime
# FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-devel

# RUN apt-get update; apt-get install -y build-essential libssl-dev python3 python3-dev python3-pip
# RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN pip3 install --upgrade pip
# RUN pip3 install --no-cache-dir torch torchvision torchaudio pandas numpy scikit-learn scipy pillow

# conda install pytorch torchvision torchaudio cudatoolkit=11.5 -c pytorch
# conda install numpy grpcio pyyaml psutil google-api-python-client cryptography
# conda install sphinx sphinx_rtd_theme recommonmark pydocstyle isort flake8 black click pytest-xdist
# conda install pandas torchmetrics wandb
# conda install pre-commit pytest
# conda install rarfile pylatex
# pip install tenseal

# conda install opacus jupyterlab matplotlib hydra-core omegaconf
# pip install crypten

# Disable prompts during package installation
ARG DEBIAN_FRONTEND=noninteractive

# Update package repository
RUN apt update
RUN apt upgrade -y

# Install required packages
RUN apt install -y git wget unzip build-essential

RUN pip3 install --no-cache-dir -U pip setuptools
RUN pip3 install --no-cache-dir jupyterlab pandas torchmetrics wandb neptune-client

# Clean apt cache
# RUN rm -rf /var/lib/apt/lists/*
RUN apt clean

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

ENV APP_HOME /nvflare
# ENV PYTHONPATH $APP_HOME:$APP_HOME/examples/splitnn

WORKDIR $APP_HOME
COPY . ./

RUN pip3 install -e .

RUN nvflare config -jt ./job_templates/

RUN cd integration/nemo/examples/peft/data/ && \
    wget -O FPB.zip https://huggingface.co/datasets/financial_phrasebank/resolve/main/data/FinancialPhraseBank-v1.0.zip?download=true && \
    unzip FPB.zip

# Run a simple test FL simulation with 2 clients
# CMD ["nvflare simulator -n 2 -t 2 -w /tmp/nvflare/hello-numpy-sag examples/hello-world/hello-numpy-sag/jobs/hello-numpy-sag"]
