#!/bin/bash

# Base Debian 10 Image VM
# gcloud compute instances create nvflare-test-t4 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=network-tier=PREMIUM,private-network-ip=10.164.15.220,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/ml-images/global/images/c0-deeplearning-common-cu113-v20221215-debian-10,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

# Base Ubuntu 22.04 Minimal Image VM
# gcloud compute instances create nvflare-ubuntu --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=network-tier=PREMIUM,private-network-ip=10.164.15.221,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2204-jammy-v20230124,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

#
# Debian & Ubuntu, EU & US Disk Images
#
# gcloud compute images create nvflare-dev-image-ubuntu-1-eu --project=stromasys-projects --source-disk=nvflare-ubuntu --source-disk-zone=europe-west4-a --storage-location=eu
# gcloud compute images create nvflare-dev-image-ubuntu-1-us --project=stromasys-projects --source-disk=nvflare-ubuntu --source-disk-zone=europe-west4-a --storage-location=us

# gcloud compute images create nvflare-dev-image-debian-1-eu --project=stromasys-projects --source-disk=nvflare-test-t4 --source-disk-zone=europe-west4-a --storage-location=eu
# gcloud compute images create nvflare-dev-image-debian-1-us --project=stromasys-projects --source-disk=nvflare-test-t4 --source-disk-zone=europe-west4-a --storage-location=us

#
# nvflare-network VPC With MTU 8896
#
# gcloud compute networks create nvflare-network --project=stromasys-projects --subnet-mode=auto --mtu=8896 --bgp-routing-mode=regional
# gcloud compute firewall-rules create nvflare-network-allow-icmp --project=stromasys-projects --network=projects/stromasys-projects/global/networks/nvflare-network --description=Allows\ ICMP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=icmp
# gcloud compute firewall-rules create nvflare-network-allow-ssh --project=stromasys-projects --network=projects/stromasys-projects/global/networks/nvflare-network --description=Allows\ TCP\ connections\ from\ any\ source\ to\ any\ instance\ on\ the\ network\ using\ port\ 22. --direction=INGRESS --priority=65534 --source-ranges=0.0.0.0/0 --action=ALLOW --rules=tcp:22
# Also add rule to open ports 8002-8003 for tagged VMs in VPC (nvflare-node tag)

#
# EU Public IPs
#
# gcloud compute addresses create nvflare-test-a100-ip --region=europe-west4
# gcloud compute addresses create nvflare-test-t4-ip --region=europe-west4
# gcloud compute addresses describe nvflare-test-a100-ip
# gcloud compute addresses describe nvflare-test-t4-ip
# 34.147.38.222
# 34.91.73.216

#
# nvflare-test-a100 - a100 GPU - 10.164.15.210 - 34.147.38.222 (Static)
#
#gcloud compute instances create nvflare-test-a100 --project=stromasys-projects --zone=europe-west4-a --machine-type=a2-highgpu-1g --network-interface=address=34.147.38.222,network-tier=PREMIUM,private-network-ip=10.164.15.210,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-a100 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

# nvflare-test-t4-1 - t4 GPU - 10.164.15.211 - 34.91.73.216 (Static)
# nvflare-test-t4-2 - t4 GPU - 10.164.15.212 - 34.91.118.166 (Static)
# nvflare-test-t4-3 - t4 GPU - 10.164.15.213 - 34.91.49.55 (Static)
# nvflare-test-t4-4 - t4 GPU - 10.164.15.214 - 34.91.144.199 (Static)
# nvflare-test-t4-5 - t4 GPU - 10.164.15.215 - 34.91.43.51 (Static)
# nvflare-test-t4-6 - t4 GPU - 10.164.15.216 - 34.91.31.240 (Static)

#gcloud compute instances create nvflare-test-t4-1 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=address=34.91.73.216,network-tier=PREMIUM,private-network-ip=10.164.15.211,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
#gcloud compute instances create nvflare-test-t4-2 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=address=34.91.118.166,network-tier=PREMIUM,private-network-ip=10.164.15.212,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
#gcloud compute instances create nvflare-test-t4-3 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=address=34.91.49.55,network-tier=PREMIUM,private-network-ip=10.164.15.213,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
#gcloud compute instances create nvflare-test-t4-4 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=address=34.91.144.199,network-tier=PREMIUM,private-network-ip=10.164.15.214,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
#gcloud compute instances create nvflare-test-t4-5 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=address=34.91.43.51,network-tier=PREMIUM,private-network-ip=10.164.15.215,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
#gcloud compute instances create nvflare-test-t4-6 --project=stromasys-projects --zone=europe-west4-a --machine-type=n1-standard-8 --network-interface=address=34.91.31.240,network-tier=PREMIUM,private-network-ip=10.164.15.216,subnet=default --metadata=enable-oslogin=true --maintenance-policy=TERMINATE --provisioning-model=SPOT --service-account=1095933948428-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-t4 --tags=nvflare-test --create-disk=auto-delete=yes,boot=yes,device-name=nvflare-test,image=projects/stromasys-projects/global/images/nvflare-dev-image-debian-1-eu,mode=rw,size=50,type=projects/stromasys-projects/zones/europe-west4-a/diskTypes/pd-ssd --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
